### PR TITLE
feat: remove shadowed wrapper

### PR DESCRIPTION
**Pull request by ChasNelson1990**
## Description

This PR does 2 things:

1. it merges all of the `.wrapper` CSS into one bit - wrappers should be identical across pages so I think this makes sense. This change definitely belongs here.
2. it sets the `.main` background colour to `primary10` (keeping the `.homepage .hero` as `light`. This requires a knock-on to make sure that sidebar modules have a background colour of `light`. I am not 100% sure if this change belongs here or in ZaRR - thoughts @A-Souhei?

relates (but is not dependent on) fjelltopp/ckanext-zarr#44

## Checklist

- [ ] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [x] I have developed these changes in discussion with the appropriate project manager.
- [x] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [x] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own code.
- [x] I have assigned at least one reviewer.
- [x] I have assigned at least one label to this PR: "patch", "minor", "major".

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
Not quite sure how this got closed?

**Review by A-Souhei — APPROVED** [review]

**Review by A-Souhei — CHANGES_REQUESTED** [review]
@ChasNelson1990 ,
With changing the background we will also need to change the dataset read page, or shall we just keep the dataset read page background white? 
image
image

I want to think that in ZaRR it could be easier but I am not sure

**Comment by ChasNelson1990** [comment]
Oh, yes, let's make the dataset read pages white.

image

Probably all things under the tabs should be white?

**Comment by A-Souhei** [comment]
There seems to be a fine grain in the background.

image

I make an update to remove it.

The 'add dataset' button changed, looking to fix it as well :
image
(it is a bug from another PR, I will make another PR)

**Comment by A-Souhei** [comment]
Added a commit to make the elements under nav-tabs (organization, group, package, user, sysadmin) to have a light background except for pages with list of packages. Also added a darker border for group topic squares.

image
image

packages' lists do not have the primary10 background applied:
image

**Review by A-Souhei — COMMENTED** [review]
@ChasNelson1990 I have reviewed this PR and added a few changes for your review as well.

**Comment by ChasNelson1990** [comment]
LGTM @A-Souhei

**Review by A-Souhei — APPROVED** [review]

**Pull request merged**
